title: Calculus
author: Hao-Ming Peng

parse:
  myst_enable_extensions: 
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
    - attrs_block

sphinx:
  config:
    html_theme_options:
      use_sidenotes: true
    html_css_file:
      - "css/custom.css"
  extra_extensions:
    - sphinx_proof
